#!/usr/bin/env python3
"""PHASE 8 -- write every computed quantity into data/CANONICAL_NUMBERS.yaml.

Chem-151 | S.T. Yau High School Science Award (Asia) 2026 | Palaash Gang

CLAUDE.md §5: no numeric result may be hard-coded in any .tex file, and
`status: VERIFIED` is set only when the value is derived from a real dataset BY
A SCRIPT, never by hand.  This is that script for the computational arm.

Every emitted key carries the ORCA output file it came from in
`source_dataset`, so that a referee can go from a number in the report to the
file that produced it in one step.

WHAT IS DELIBERATELY NOT EMITTED
  * anything derived from the Stage-1 outline's alpha values.  Rule 3 of the
    YAML header: nothing here is pre-filled from the outline.  The outline's
    alpha(Pb/Cu) = 3.63 and alpha(Pb/Zn) = 7.03 are CLAIMS TO BE TESTED; the
    -RT ln(alpha) arithmetic is reported in RESULTS_SUMMARY.md §5 and the
    corresponding keys stay PENDING until alpha is derived from the AAS data.
  * the energy-decomposition terms and f_orb.  Multiwfn is not installed;
    attack A01 stays OPEN and DFT_PROTOCOL.md §4.3's fallback binds.
  * the Pb-O bond-length validation deviation.  It needs a literature value
    that has cleared verify_dois.py and been read (CLAUDE.md §6).

    python dft/analysis/emit_canonical.py            # rewrite the DFT block
    python dft/analysis/emit_canonical.py --print    # print it, change nothing
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(ROOT / "dft" / "structures"))
sys.path.insert(0, str(ROOT / "analysis" / "src"))

from orca_parse import OPEN_SHELL, parse_all                       # noqa: E402
from thermo import REACTIONS, REACTIONS_PB8, dg_exchange, gibbs    # noqa: E402
from thermo import DG_GAS_TO_1M, DG_WATER_REF                      # noqa: E402
from denticity import measure                                      # noqa: E402
from run_hemidirection import row as hemi_row                      # noqa: E402

YAML = ROOT / "data" / "CANONICAL_NUMBERS.yaml"
START = "# DFT — BINDING THERMOCHEMISTRY  —  §4.6, Table 4.7, Finding 4"
END = "# DFT — ENERGY DECOMPOSITION  —  §4.7, Table 4.8, Finding 5"

STATES = ("P0", "P1", "P2")
METALS = ("Pb", "Cu", "Zn")
AQUO = {"Pb": "pb_aquo6", "Cu": "cu_aquo6", "Zn": "zn_aquo6"}


# Decimal places by unit.  REACTIONS.md §5.4: significant figures are matched to
# the METHOD's resolution, not to the printed precision of the output file.
# "A ddG quoted to 0.01 kJ/mol from DFT would be a claim the method cannot
# support" -- so free energies are stored to 0.1 kJ/mol.  Optimised bond lengths
# are meaningful to 0.001 A; angles to 0.1 deg.
DP = {"kJ/mol": 1, "angstrom": 3, "degree": 1, "dimensionless": 4,
      "cm^-1": 2, "%": 1, "count": 0}


def entry(key, value, units, source, note=None, unc=None, n=None) -> str:
    dp = DP.get(units, 4)
    def fmt(x):
        if x is None:
            return "null"
        if isinstance(x, (int, np.integer)) or dp == 0:
            return str(int(round(float(x))))
        return f"{round(float(x), dp):.{dp}f}"
    v = fmt(value)
    u = fmt(unc)
    nn = "null" if n is None else str(n)
    out = [f"{key}:",
           f"  value: {v}",
           f"  uncertainty: {u}",
           f"  n: {nn}",
           f'  units: "{units}"',
           f'  source_dataset: "{source}"',
           f"  status: {'VERIFIED' if value is not None else 'PENDING'}"]
    if note:
        out.append(f'  note: "{note}"')
    return "\n".join(out) + "\n"


def build() -> str:
    jobs = parse_all()
    G = gibbs(jobs)
    geo = {n: measure(n) for n in
           [f"{m.lower()}_{s}_cplx" for m in METALS for s in STATES]
           + list(AQUO.values()) + ["pb_aquo8"]}
    hemi = {n: hemi_row(n)[2] for n in geo}
    dg = {(r.metal, r.state): dg_exchange(r, G)["total"] for r in REACTIONS}

    L: list[str] = []
    A = L.append

    A("# " + "-" * 78)
    A(f"{START}")
    A("# " + "-" * 78)
    A("#")
    A("# GENERATED BY dft/analysis/emit_canonical.py FROM THE ORCA OUTPUT FILES.")
    A("# Do not edit by hand. Re-run the script instead.")
    A("#")
    A("# All seventeen production jobs terminated normally, converged, ran analytic")
    A("# frequencies and carry ZERO imaginary modes — dft/analysis/integrity_gate.py.")
    A("# G = FINAL SINGLE POINT ENERGY + G-E(el), the composition audited in")
    A("# dft/analysis/G_COMPOSITION.md. ORCA 6.1.1 applied Grimme quasi-RRHO by")
    A("# default with a 100 cm^-1 reference frequency, which is what protocol §3.4")
    A("# specifies.")
    A("#")
    A("# KEYS ARE RESOLVED BY PROTONATION STATE. The earlier per-metal keys")
    A("# (dg_exchange_pb_kJ_per_mol, coordination_number_pb,")
    A("# hemidirection_displacement_pb_ang, void_hemisphere_angle_pb_deg,")
    A("# bond_length_pb_o_mean_ang and their Cu/Zn counterparts) are REMOVED: they")
    A("# are ill-defined without a protonation state, because dG_exchange for lead")
    A("# runs from -9.5 kJ/mol at P0 to -190.5 kJ/mol at P2. Their replacements")
    A("# carry an explicit _P0 / _P1 / _P2 suffix.")
    A("")

    # ── exchange free energies ───────────────────────────────────────────────
    A("# --- Aquo-ligand exchange free energies (attack A04: never naked-ion) ---")
    A("")
    for r in REACTIONS:
        m, s = r.metal, r.state
        src = (f"dft/outputs/{r.complex}/{r.complex}.out; "
               f"dft/outputs/{r.aquo}/{r.aquo}.out; "
               f"dft/outputs/{r.ligand}/{r.ligand}.out; "
               f"dft/outputs/water/water.out")
        A(entry(f"dg_exchange_{m.lower()}_{s}_kJ_per_mol", dg[(m, s)], "kJ/mol",
                src,
                f"[M(H2O)6]2+ + L -> [M(L)(H2O)4]q + 2 H2O; x=2, dn=+1; "
                f"{r.denticity}; includes dG_ss = "
                f"{r.dg_ss:.2f} kJ/mol (dft/analysis/thermo.py)"))
        A("")

    # ── cross-metal differences ──────────────────────────────────────────────
    A("# --- Cross-metal differences. Negative = the galloyl site prefers Pb(II). ---")
    A("")
    for a, b in (("Pb", "Cu"), ("Pb", "Zn"), ("Cu", "Zn")):
        for s in STATES:
            matched = (geo[f"{a.lower()}_{s}_cplx"]["denticity"]
                       == geo[f"{b.lower()}_{s}_cplx"]["denticity"])
            note = ("denticity-MATCHED, like-for-like, quotable" if matched else
                    "DENTICITY MISMATCH — "
                    f"{a} {geo[f'{a.lower()}_{s}_cplx']['denticity']}, "
                    f"{b} {geo[f'{b.lower()}_{s}_cplx']['denticity']}; "
                    "must carry a stated caveat in the table itself (attack A31)")
            A(entry(f"ddg_{a.lower()}_{b.lower()}_{s}_kJ_per_mol",
                    dg[(a, s)] - dg[(b, s)], "kJ/mol", "derived; dft/analysis/thermo.py",
                    note))
            A("")

    # ── denticity and first-shell geometry ───────────────────────────────────
    A("# --- Denticity, MEASURED on every optimised complex (attack A31, §3.7). ---")
    A("# Both M-O(galloyl) distances are stored INDIVIDUALLY and never averaged:")
    A("# averaging is exactly what would hide a monodentate structure.")
    A("")
    for m in METALS:
        for s in STATES:
            n = f"{m.lower()}_{s}_cplx"
            g = geo[n]
            src = f"dft/outputs/{n}/{n}.xyz"
            A(entry(f"m_o_galloyl_1_{m.lower()}_{s}_ang", g["galloyl"][0][1],
                    "angstrom", src,
                    f"shorter of the two vicinal galloyl O; first-shell cutoff "
                    f"{g['cutoff']:.2f} A"))
            A("")
            A(entry(f"m_o_galloyl_2_{m.lower()}_{s}_ang", g["galloyl"][1][1],
                    "angstrom", src,
                    f"longer of the two vicinal galloyl O; verdict {g['denticity']}"))
            A("")
            A(entry(f"n_galloyl_donors_{m.lower()}_{s}", g["n_bound"], "count", src,
                    f"denticity verdict: {g['denticity']}"))
            A("")
            A(entry(f"coordination_number_{m.lower()}_{s}", g["cn"], "count", src,
                    f"first-shell O within {g['cutoff']:.2f} A "
                    f"= {g['n_lig_shell']} galloyl + {g['n_water_shell']} water"))
            A("")
            A(entry(f"n_water_first_shell_{m.lower()}_{s}", g["n_water_shell"],
                    "count", src,
                    f"cluster contains {g['n_water_cluster']} waters; "
                    f"{g['n_water_cluster'] - g['n_water_shell']} beyond the cutoff"))
            A("")

    # ── hemidirection ────────────────────────────────────────────────────────
    A("# --- Hemidirection, MEASURED never asserted (attack A14, §5). ---")
    A("# d~ is the primary quantity: normalising by the mean bond length removes the")
    A("# trivial dependence on ionic radius, without which Pb would score higher")
    A("# merely for having longer bonds.")
    A("")
    for name in [f"{m.lower()}_{s}_cplx" for m in METALS for s in STATES] \
            + ["pb_aquo6", "pb_aquo8", "cu_aquo6", "zn_aquo6"]:
        r = hemi[name]
        src = f"dft/outputs/{name}/{name}.xyz; analysis/src/hemidirection.py"
        A(entry(f"hemi_dtilde_{name}", r.normalised_displacement, "dimensionless",
                src, f"n donors {r.n_donors}; verdict {r.verdict}"))
        A("")
        A(entry(f"hemi_displacement_{name}_ang", r.displacement, "angstrom", src,
                "distance of the metal from the donor-set centroid"))
        A("")
        A(entry(f"void_angle_{name}_deg",
                r.void_angle, "degree", src,
                "angular clearance of the donor-free hemisphere, after "
                "Shimoni-Livny et al."
                + ("" if r.void_angle is not None
                   else "; HOLODIRECTED — donor set symmetric, no void direction exists")))
        A("")
        A(entry(f"mean_m_o_{name}_ang", r.mean_bond_length, "angstrom", src,
                f"mean first-shell M-O over {r.n_donors} donors",
                unc=float(np.std(r.bond_lengths, ddof=1)) if r.n_donors > 1 else None,
                n=r.n_donors))
        A("")

    # ── spin ─────────────────────────────────────────────────────────────────
    A("# --- <S^2> for every open-shell Cu(II) d9 doublet (attack A02, §3.2). ---")
    A("")
    for name in [n for n in ("cu_aquo6", "cu_P0_cplx", "cu_P1_cplx", "cu_P2_cplx")]:
        j = jobs[name]
        A(entry(f"s_squared_{name}", j.s2, "dimensionless",
                f"dft/outputs/{name}/{name}.out",
                f"ideal 0.750; deviation {j.s2 - 0.750:+.6f} "
                f"({j.s2_deviation_pct:+.3f}%); UKS, multiplicity 2, charge "
                f"{j.charge:+d}"))
        A("")
    s2max = max(jobs[n].s2 for n in OPEN_SHELL)
    A(entry("s_squared_cu_max", s2max, "dimensionless",
            "dft/outputs/cu_*/*.out",
            f"largest <S^2> over the four Cu species; deviation from ideal "
            f"{(s2max - 0.750) / 0.750 * 100:+.3f}%. Below the 0.80 flagging "
            f"threshold, so spin contamination is negligible"))
    A("")

    # ── integrity ────────────────────────────────────────────────────────────
    A("# --- Integrity gate (§3.4). Reported because a referee will ask. ---")
    A("")
    A(entry("n_dft_jobs_complete", len(jobs), "count",
            "dft/outputs/; dft/analysis/integrity_gate.py",
            "terminated normally AND optimiser converged AND frequencies ran "
            "AND .hess on disk"))
    A("")
    A(entry("n_imaginary_frequencies_total", int(sum(j.n_imag for j in jobs.values())),
            "count", "dft/outputs/; dft/analysis/integrity_gate.py",
            "summed over all seventeen species; every reported structure is a "
            "true minimum"))
    A("")
    lowest = min(j.lowest_real for j in jobs.values())
    lowest_job = min(jobs, key=lambda n: jobs[n].lowest_real)
    A(entry("lowest_real_mode_cm1", lowest, "cm^-1",
            f"dft/outputs/{lowest_job}/{lowest_job}.out",
            f"smallest real vibrational mode in the whole species set "
            f"({lowest_job}); motivates the quasi-RRHO treatment"))
    A("")
    A(entry("n_species_with_mode_below_100cm1",
            int(sum(1 for j in jobs.values() if j.lowest_real < 100.0)), "count",
            "dft/outputs/; dft/analysis/integrity_gate.py",
            "of 17; ORCA 6.1.1 applied Grimme quasi-RRHO by default with a "
            "100 cm^-1 reference frequency"))
    A("")

    # ── standard state ───────────────────────────────────────────────────────
    A("# --- Standard-state corrections (§3.5). Recomputed from R, T and c. ---")
    A("")
    A(entry("dg_gas_to_1molar_kJ_per_mol", DG_GAS_TO_1M, "kJ/mol",
            "dft/analysis/thermo.py",
            "RT ln(24.46) per mole of species at 298.15 K"))
    A("")
    A(entry("dg_water_pure_liquid_kJ_per_mol", DG_WATER_REF, "kJ/mol",
            "dft/analysis/thermo.py",
            "RT ln(55.34) per water released; water is referenced to its "
            "pure-liquid standard state, not 1 mol/L"))
    A("")
    A(entry("dg_ss_exchange_kJ_per_mol", DG_GAS_TO_1M - 2 * DG_WATER_REF, "kJ/mol",
            "dft/analysis/thermo.py",
            "net standard-state term for each of the nine exchange reactions "
            "(dn=+1, x=2); identical across all nine so it cancels exactly in "
            "every ddG"))
    A("")

    # ── Pb coordination number, limitations material ─────────────────────────
    A("# --- Pb(II) coordination number at DFT level. LIMITATIONS MATERIAL, §5.3. ---")
    A("")
    e = {n: jobs[n].e_final for n in jobs}
    gt = {n: jobs[n].g_minus_eel for n in jobs}
    HK = 2625.499639
    d_e = (e["pb_aquo8"] - e["pb_aquo6"] - 2 * e["water"]) * HK
    d_th = (gt["pb_aquo8"] - gt["pb_aquo6"] - 2 * gt["water"]) * HK
    d_ss = (-2) * DG_GAS_TO_1M + 2 * DG_WATER_REF
    A(entry("dg_pb_cn6_to_cn8_kJ_per_mol", d_e + d_th + d_ss, "kJ/mol",
            "dft/outputs/pb_aquo6/pb_aquo6.out; dft/outputs/pb_aquo8/pb_aquo8.out; "
            "dft/outputs/water/water.out",
            "[Pb(H2O)6]2+ + 2 H2O -> [Pb(H2O)8]2+. POSITIVE = CN=6 favoured. The "
            "GFN2-xTB CN=8 preference does NOT survive at DFT with SMD"))
    A("")
    A(entry("de_pb_cn6_to_cn8_electronic_kJ_per_mol", d_e, "kJ/mol",
            "dft/outputs/pb_aquo6/pb_aquo6.out; dft/outputs/pb_aquo8/pb_aquo8.out; "
            "dft/outputs/water/water.out",
            "electronic component only; NEGATIVE, i.e. it agrees with GFN2 in "
            "direction. The thermal/entropic term is what reverses the preference"))
    A("")
    for n in ("pb_aquo6", "pb_aquo8"):
        g = geo[n]
        inner = [d for d, _, _ in g["shell"]]
        A(entry(f"mean_pb_o_{n}_ang", float(np.mean(inner)), "angstrom",
                f"dft/outputs/{n}/{n}.xyz",
                f"mean FIRST-SHELL Pb-O; cluster holds {g['n_water_cluster']} "
                f"waters but only {g['cn']} lie within {g['cutoff']:.2f} A. "
                f"Uncertainty is the SD over the first shell, not an experimental "
                f"error",
                unc=float(np.std(inner, ddof=1)), n=len(inner)))
        A("")

    # ── explicitly still pending ─────────────────────────────────────────────
    A("# --- STILL PENDING. Not computed, not guessed. ---")
    A("")
    A(entry("ddg_pb_cu_exp_kJ_per_mol", None, "kJ/mol", "derived from alpha",
            "= -RT ln alpha(Pb/Cu), the correct experimental counterpart to the "
            "computed value. PENDING because alpha must come from the AAS data, "
            "not from the Stage-1 outline (YAML rule 3). The arithmetic is in "
            "dft/analysis/selectivity.py"))
    A("")
    A(entry("ddg_pb_zn_exp_kJ_per_mol", None, "kJ/mol", "derived from alpha",
            "= -RT ln alpha(Pb/Zn); PENDING for the same reason"))
    A("")
    A(entry("validation_deviation_pct", None, "%", "dft/validation",
            "deviation of the computed mean Pb-O from a published EXAFS / X-ray "
            "hydration structure. PENDING: needs a reference that has cleared "
            "verify_dois.py and been read (CLAUDE.md §6)"))
    A("")
    A(entry("e_int_counterpoise_pb_kJ_per_mol", None, "kJ/mol", "dft/analysis",
            "counterpoise-corrected interaction energy, one representative case "
            "per metal (§3.6). NOT RUN in this session"))
    A("")
    A("")
    return "\n".join(L)


def main() -> int:
    block = build()
    if "--print" in sys.argv:
        print(block)
        return 0

    text = YAML.read_text()
    i = text.index(START)
    # back up to the opening dashed comment line of that header
    i = text.rindex("# " + "-" * 78, 0, i)
    j = text.index(END)
    j = text.rindex("# " + "-" * 78, 0, j)
    YAML.write_text(text[:i] + block + text[j:])
    n_keys = block.count("\n  status:")
    n_ver = block.count("status: VERIFIED")
    print(f"data/CANONICAL_NUMBERS.yaml — DFT block rewritten: "
          f"{n_keys} keys, {n_ver} VERIFIED, {n_keys - n_ver} PENDING.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
